### ISSUE TITLE
Pretrained Weights

### ISSUE THREAD

**Issue by betegon** [pquochuy/idsegan#3]
Hi @pquochuy 

Firstly, congratulations on your hard work!

I would like to give a try to the network, could you provide pre-trained weights?

If so, it would be a great step towards letting people start training from that weights or just to try the model by denoising some files. 

Also, it would be epic if you could provided an input and output audio of the network, to allow people check that installation is working properly. This will also help people debug errors found.

thank you a lot,

Regards.

**Comment by pquochuy** [comment]
Hi @betegon,
I am retrieving the models weights from our servers, but unfortunately the internet is too slow at the moment due to the outbreak. I think it is even slower if I upload the models somewhere. But please hang on here, once the models are ready to share, I will let you know again.

thank you and stay safe.

**Comment by betegon** [comment]
Hi @pquochuy 

Yes! speed has been slowed down almost in any part of the globe. 

Thank you so much for letting me know, let's wait then.

I hope this ends soon!

Thanks again and stay safe you too.

**Comment by kwanUm** [comment]
Checking to see whether there's any update on the above :)
output samples would be great too!

**Comment by betegon** [comment]
@kwanUm No, at least for now. 
Yes, output samples to compare results would be so great!

**Comment by pquochuy** [comment]
@betegon @kwanUm 
I've managed to upload the wave files corresponding to DSEGAN with depth 2 that can be used for comparison purpose. Please find them here:

[Link](https://entuedu-my.sharepoint.com/:f:/g/personal/phan0035_e_ntu_edu_sg/Er0GpcalxwpIsvugbc3hkMwBmqRkbxvQ9yxd3CU9YtT17w?e=3L3luh)

The pretrained models (~10Gb for 5 model checkpoints) would take much longer time as I have very limited bandwidth at home. I will let you know if they are ready.

**Comment by pquochuy** [comment]
@betegon @kwanUm 

Sorry for taking a long time. The DSEGAN models (depth of 2) are available here:

[Link](https://zenodo.org/record/4066669)
