### ISSUE TITLE
AttributeError: force_gen

### ISSUE THREAD

**Issue by kingback2019** [pquochuy/idsegan#4]
Hello,when I run the task "./create_training_tfrecord.sh ",I don't know what's wrong with it? Anyone else have the same trouble?

**Comment by kingback2019** [comment]
the wrong position appears here in the file make_tfrecords.py
    
if os.path.exists(out_filepath) and not opts.force_gen:
        raise ValueError(
            'ERROR: {} already exists. Set force flag (--force-gen) to '
            'overwrite. Skipping this speaker.'.format(out_filepath))

**Comment by pquochuy** [comment]
@kingback2019 It seems that there was an existing file and you did not specify overwriting option. You can delete the existing file or set the --force-gen flag to overwrite it.

**Comment by kingback2019** [comment]
> @kingback2019 It seems that there was an existing file and you did not specify overwriting option. You can delete the existing file or set the --force-gen flag to overwrite it.
Thanks for your answer, I finally skipped this step and no more errors were reported.
